image:
  file: .gitpod.Dockerfile

ports:
- port: 8888
  onOpen: open-browser

tasks:
  - init: cp -r /workspace/gpjlab/.jupyter /home/gitpod/ && pip install -r requirements.txt
    command: jupyter lab
